#!/bin/bash

if [[ -z $VIRTUAL_ENV ]]; then
    source .env/bin/activate
fi

if [[ $1 =~ ^(server)$ ]]; then
    cd server
    flask --debug run

elif [[ $1 =~ ^(bot)$ ]]; then
    cd bot
    python main.py

elif [[ $1 =~ ^(log)$ ]]; then
    cat bot.log

fi
